# JRDB
export JRDB_USERNAME="YOUR JRDB USERNAME"
export JRDB_PASSWORD="YOUR JRDB PASSWORD"

# Azure Portal > Storage Account > Access Key
export AZURE_STORAGE_ACCOUNT="YOUR AZURE STORAGE ACCOUNT"
export AZURE_STORAGE_KEY1="YOUR AZURE STORAGE KEY1"

# Azure Portal > Container Registry > KEY
export USERNAME="YOUR USER NAME"
export PASSWORD="YOUR PASSWORD"
export REGISTRY="YOUR REGISTRY NAME"
